# Generated by Django 4.1 on 2024-05-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prametros',
            new_name='Parametros',
        ),
    ]
