# Generated by Django 4.1 on 2024-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modrotativo',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
