# Generated by Django 4.1 on 2024-06-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movmensalista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModRotativo',
            new_name='MovRotativo',
        ),
    ]
